[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solado_cash = "GtviumFyW3zVqLCmxJZpBSbQT4LePTyMAubHVZA4DT7X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/longtran/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**.ts"
